; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
AppName=MyProgram
AppVersion=1.0
DefaultDirName={pf}\SetupProgram
OutputDir=C:\MySetupFiles

[Files]
Source: "C:\Users\User\source\repos\WindowsFormsApp1\WindowsFormsApp1.sln"; DestDir: "{app}"; 
[Types]
Name: "full"; Description: "Full installation";